name: Build and Deploy to Cloud Run

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  REGION: asia-southeast2
  GAR_LOCATION: asia-southeast2-docker.pkg.dev/klinik-marisembuh/jurnalastral-bot
  IMAGE_NAME: jurnalastral-bot
  SERVICE_ACCOUNT: github-actions@klinik-marisembuh.iam.gserviceaccount.com
  WIF_PROVIDER: projects/547319188901/locations/global/workloadIdentityPools/github-marisembuh-api/providers/github-marisembuh-api

permissions:
  contents: "read"
  id-token: "write"

jobs:
  build-deploy-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: Authenticate with Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: access_token
          workload_identity_provider: ${{env.WIF_PROVIDER}}
          service_account: ${{env.SERVICE_ACCOUNT}}
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGION}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Tag Docker image and push to Google Artifact Registry
        id: docker-push-tagged
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.GAR_LOCATION }}/${{env.IMAGE_NAME}}:${{ github.sha }}
            ${{ env.GAR_LOCATION }}/${{env.IMAGE_NAME}}:latest

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: "jurnalastral-bot"
          image: ${{ env.GAR_LOCATION }}/${{env.IMAGE_NAME}}:latest
          region: ${{env.REGION}}
          flags: "--allow-unauthenticated"
          env_vars: |
            TELEGRAM_BOT_TOKEN=${{secrets.TELEGRAM_BOT_TOKEN}}
            TELEGRAM_BOT_WEBHOOK_URI=${{secrets.TELEGRAM_BOT_WEBHOOK_URI}}
            TELEGRAM_BOT_URI=${{secrets.TELEGRAM_BOT_URI}}
            DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}
            DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
            DATABASE_HOST=${{secrets.DATABASE_HOST}}
            DATABASE_PORT=${{secrets.DATABASE_PORT}}
            DATABASE_DBNAME=${{secrets.DATABASE_DBNAME}}
            DATABASE_DIALECT=${{secrets.DATABASE_DIALECT}}
